import { useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Plus, Target, TrendingUp, Wallet, X } from 'lucide-react';
import { calculateTotals, formatMoney, type Transaction } from '../domain/finance';
import { createSavingsEntry, createSavingsGoal, expectedCompletion, goalProgress, monthlySaved, savingsRate, type SavingsEntry, type SavingsGoal } from '../domain/savings';
import { loadSavingsEntries, loadSavingsGoals, saveSavingsEntries, saveSavingsGoals } from '../data/savingsStorage';
const tones=['evergreen','sage','gold','blue'];
export default function SavingsCenter({transactions,focus='Savings'}:{transactions:Transaction[];focus?:'Savings'|'Goals'}){
 const [goals,setGoals]=useState<SavingsGoal[]>(()=>loadSavingsGoals()); const [entries,setEntries]=useState<SavingsEntry[]>(()=>loadSavingsEntries()); const [showGoal,setShowGoal]=useState(false); const [showEntry,setShowEntry]=useState(false); const [selected,setSelected]=useState<string|undefined>();
 const totals=useMemo(()=>calculateTotals(transactions),[transactions]); const saved=entries.reduce((s,e)=>s+(e.type==='contribution'?e.amount:-e.amount),0); const month=monthlySaved(entries); const rate=savingsRate(totals.income,totals.expenses);
 function addGoal(input:Omit<SavingsGoal,'id'|'createdAt'|'updatedAt'>){const next=[createSavingsGoal(input),...goals];setGoals(next);saveSavingsGoals(next);setShowGoal(false)}
 function addEntry(input:Omit<SavingsEntry,'id'|'createdAt'>){const entry=createSavingsEntry(input);const nextEntries=[entry,...entries];const nextGoals=input.goalId?goals.map(g=>g.id===input.goalId?{...g,savedAmount:Math.max(0,g.savedAmount+(input.type==='contribution'?input.amount:-input.amount)),updatedAt:new Date().toISOString()}:g):goals;setGoals(nextGoals);setEntries(nextEntries);saveSavingsGoals(nextGoals);saveSavingsEntries(nextEntries);setShowEntry(false);setSelected(undefined)}
 const visibleGoals=focus==='Goals'?goals:goals.slice(0,3);
 return <section className="savings-page"><div className="savings-hero"><div><p className="section-kicker">{focus==='Goals'?'Goal planning':'Savings center'}</p><h2>{focus==='Goals'?'Give your money somewhere to go.':'Build savings with intention.'}</h2><p className="muted">Track what you save, why you are saving, and how close you are.</p></div><div className="savings-actions"><button className="secondary-button" onClick={()=>setShowEntry(true)}><Plus size={16}/> Add saving</button><button className="primary-button" onClick={()=>setShowGoal(true)}><Target size={16}/> New goal</button></div></div>
 <div className="savings-metrics"><Metric icon={Wallet} label="Total saved" value={formatMoney(saved)}/><Metric icon={TrendingUp} label="This month" value={formatMoney(month)}/><Metric icon={ArrowUpRight} label="Savings rate" value={`${rate}%`}/><Metric icon={Target} label="Active goals" value={String(goals.filter(g=>g.savedAmount<g.targetAmount).length)}/></div>
 <div className="savings-grid"><div className="panel savings-goals"><div className="panel-header"><div><h2>{focus==='Goals'?'Your goals':'Goals to keep you moving'}</h2><p>{goals.length?'Progress based on actual contributions.':'Create a goal for something that matters to you.'}</p></div></div>{visibleGoals.length?<div className="goal-list">{visibleGoals.map(g=><GoalCard key={g.id} goal={g} entries={entries} onAdd={()=>{setSelected(g.id);setShowEntry(true)}} onWithdraw={()=>{setSelected(g.id);setShowEntry(true)}}/>)}</div>:<div className="savings-empty"><div className="goal-icon"><Target size={22}/></div><strong>No savings goals yet</strong><span>Create your first goal and start tracking progress.</span><button className="secondary-button" onClick={()=>setShowGoal(true)}><Plus size={15}/> Create goal</button></div>}</div>
 <div className="panel savings-side"><div className="panel-header"><div><h2>Your saving rhythm</h2><p>A transparent view of recent saving activity.</p></div></div><div className="rhythm"><div className="rhythm-total"><span>Saved this month</span><strong>{formatMoney(month)}</strong></div><div className="rhythm-track"><span style={{width:`${Math.min(100,Math.max(0,totals.income?month/totals.income*100:0))}%`}}/></div><p>{totals.income?`${rate}% of your recorded income is currently left after expenses.`:'Add income and expenses to calculate your savings rate.'}</p></div><div className="divider"/><div className="panel-header compact"><div><h2>Recent saving activity</h2></div></div>{entries.slice(0,5).map(e=><div className="saving-entry" key={e.id}><span className={e.type==='contribution'?'entry-positive':'entry-negative'}>{e.type==='contribution'?<ArrowUpRight size={15}/>:<ArrowDownRight size={15}/>}</span><div><strong>{e.note||'Savings movement'}</strong><small>{new Date(e.date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</small></div><b className={e.type==='contribution'?'positive':''}>{e.type==='contribution'?'+':'-'}{formatMoney(e.amount)}</b></div>)}{!entries.length&&<div className="side-empty">Your saving activity will appear here.</div>}</div></div>
 {showGoal&&<GoalComposer onClose={()=>setShowGoal(false)} onSave={addGoal}/>} {showEntry&&<EntryComposer goals={goals} selectedGoal={selected} onClose={()=>{setShowEntry(false);setSelected(undefined)}} onSave={addEntry}/>}</section>
}
function Metric({icon:Icon,label,value}:{icon:typeof Wallet;label:string;value:string}){return <div className="saving-metric"><span><Icon size={16}/></span><div><small>{label}</small><strong>{value}</strong></div></div>}
function GoalCard({goal,entries,onAdd,onWithdraw}:{goal:SavingsGoal;entries:SavingsEntry[];onAdd:()=>void;onWithdraw:()=>void}){const progress=goalProgress(goal);return <article className="goal-card"><div className="goal-card-top"><div className="goal-badge" data-tone={goal.color}><Target size={17}/></div><div className="goal-copy"><strong>{goal.name}</strong><span>{expectedCompletion(goal,entries)}</span></div><b>{progress}%</b></div><div className="goal-bar"><span style={{width:`${progress}%`}}/></div><div className="goal-numbers"><span>{formatMoney(goal.savedAmount)} saved</span><span>{formatMoney(Math.max(0,goal.targetAmount-goal.savedAmount))} remaining</span></div><div className="goal-card-actions"><button className="secondary-button" onClick={onAdd}><Plus size={14}/> Add</button><button className="text-button" onClick={onWithdraw}>Withdraw</button></div></article>}
function GoalComposer({onClose,onSave}:{onClose:()=>void;onSave:(input:Omit<SavingsGoal,'id'|'createdAt'|'updatedAt'>)=>void}){const[name,setName]=useState('');const[target,setTarget]=useState('');const[date,setDate]=useState('');const[error,setError]=useState('');function submit(e:React.FormEvent){e.preventDefault();const amount=Number(target);if(!name.trim())return setError('Give your goal a name.');if(!Number.isFinite(amount)||amount<=0)return setError('Enter a target greater than ₹0.');onSave({name:name.trim(),targetAmount:amount,savedAmount:0,targetDate:date||undefined,color:tones[Math.floor(Math.random()*tones.length)]})}return <Modal title="Create savings goal" onClose={onClose}><form onSubmit={submit}><label>Goal name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Emergency fund, new laptop..." maxLength={50}/></label><label>Target amount<input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)} placeholder="₹ 0"/></label><label>Target date <span className="optional">optional</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button full">Create goal</button></form></Modal>}
function EntryComposer({goals,selectedGoal,onClose,onSave}:{goals:SavingsGoal[];selectedGoal?:string;onClose:()=>void;onSave:(input:Omit<SavingsEntry,'id'|'createdAt'>)=>void}){const[type,setType]=useState<'contribution'|'withdrawal'>('contribution');const[amount,setAmount]=useState('');const[goal,setGoal]=useState(selectedGoal||'');const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[note,setNote]=useState('');const[error,setError]=useState('');function submit(e:React.FormEvent){e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0)return setError('Enter an amount greater than ₹0.');if(type==='withdrawal'&&goal){const g=goals.find(x=>x.id===goal);if(g&&value>g.savedAmount)return setError('You cannot withdraw more than this goal has saved.')}onSave({type,amount:value,goalId:goal||undefined,date,note:note.trim()})}return <Modal title={type==='contribution'?'Add savings':'Withdraw savings'} onClose={onClose}><form onSubmit={submit}><div className="entry-switch"><button type="button" className={type==='contribution'?'active':''} onClick={()=>setType('contribution')}>Add</button><button type="button" className={type==='withdrawal'?'active':''} onClick={()=>setType('withdrawal')}>Withdraw</button></div><label>Amount<input autoFocus inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="₹ 0"/></label><label>Goal <span className="optional">optional</span><select value={goal} onChange={e=>setGoal(e.target.value)}><option value="">General savings</option>{goals.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="What are you saving for?" maxLength={100}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button full">{type==='contribution'?'Save contribution':'Save withdrawal'}</button></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="savings-modal-backdrop" onClick={onClose}><div className="savings-modal" onClick={e=>e.stopPropagation()}><div className="composer-header"><div><p className="eyebrow">Savings</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></div>{children}</div></div>}
